
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftORleftANDrightNOTleftPLUSMINUSleftTIMESDIVIDEAND BOOL DIVIDE LPAREN MINUS NOT NUMBER OR PLUS RPAREN TIMESexpr : expr PLUS expr\n            | expr MINUS expr\n            | expr TIMES expr\n            | expr DIVIDE exprexpr : expr AND expr\n            | expr OR exprexpr : NOT exprexpr : LPAREN expr RPARENexpr : NUMBERexpr : BOOL'
    
_lr_action_items = {'NOT':([0,2,3,6,7,8,9,10,11,],[2,2,2,2,2,2,2,2,2,]),'LPAREN':([0,2,3,6,7,8,9,10,11,],[3,3,3,3,3,3,3,3,3,]),'NUMBER':([0,2,3,6,7,8,9,10,11,],[4,4,4,4,4,4,4,4,4,]),'BOOL':([0,2,3,6,7,8,9,10,11,],[5,5,5,5,5,5,5,5,5,]),'$end':([1,4,5,12,14,15,16,17,18,19,20,],[0,-9,-10,-7,-1,-2,-3,-4,-5,-6,-8,]),'PLUS':([1,4,5,12,13,14,15,16,17,18,19,20,],[6,-9,-10,6,6,-1,-2,-3,-4,6,6,-8,]),'MINUS':([1,4,5,12,13,14,15,16,17,18,19,20,],[7,-9,-10,7,7,-1,-2,-3,-4,7,7,-8,]),'TIMES':([1,4,5,12,13,14,15,16,17,18,19,20,],[8,-9,-10,8,8,8,8,-3,-4,8,8,-8,]),'DIVIDE':([1,4,5,12,13,14,15,16,17,18,19,20,],[9,-9,-10,9,9,9,9,-3,-4,9,9,-8,]),'AND':([1,4,5,12,13,14,15,16,17,18,19,20,],[10,-9,-10,-7,10,-1,-2,-3,-4,-5,10,-8,]),'OR':([1,4,5,12,13,14,15,16,17,18,19,20,],[11,-9,-10,-7,11,-1,-2,-3,-4,-5,-6,-8,]),'RPAREN':([4,5,12,13,14,15,16,17,18,19,20,],[-9,-10,-7,20,-1,-2,-3,-4,-5,-6,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,2,3,6,7,8,9,10,11,],[1,12,13,14,15,16,17,18,19,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> expr PLUS expr','expr',3,'p_expr_binop','validador.py',13),
  ('expr -> expr MINUS expr','expr',3,'p_expr_binop','validador.py',14),
  ('expr -> expr TIMES expr','expr',3,'p_expr_binop','validador.py',15),
  ('expr -> expr DIVIDE expr','expr',3,'p_expr_binop','validador.py',16),
  ('expr -> expr AND expr','expr',3,'p_expr_logical','validador.py',20),
  ('expr -> expr OR expr','expr',3,'p_expr_logical','validador.py',21),
  ('expr -> NOT expr','expr',2,'p_expr_not','validador.py',25),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_expr_group','validador.py',29),
  ('expr -> NUMBER','expr',1,'p_expr_number','validador.py',33),
  ('expr -> BOOL','expr',1,'p_expr_bool','validador.py',37),
]
